INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (1,'Abacate','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (2,'Abacaxi','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (3,'Abalone','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (4,'Abiyuch','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (5,'Abóbora','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (6,'Abóbora','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (7,'Abóbora de inverno','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (8,'Abóbora de milho','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (9,'Abóbora japonesa','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (10,'Abóbora sunburst (abóbora pattypan)','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (11,'Abobrinha amarela','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (12,'Abobrinha verde','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (13,'Açafrão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (14,'Acasalar','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (15,'Acelga','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (16,'Acerola','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (17,'Açúcar','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (18,'Adobo','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (19,'Adoçante','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (20,'Ágar','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (21,'Agave','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (22,'Agente de abandono','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (23,'Agrião','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (24,'Agrião do jardim','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (25,'Água','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (26,'Aipo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (27,'Aipo selvagem','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (28,'Akutaq','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (29,'Alazão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (30,'Albizia gummifera','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (31,'Alcachofra de Jerusalém','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (32,'Alcachofra globo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (33,'Alcaçuz','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (34,'Alcaparras','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (35,'Alcaravia','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (36,'Alce','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (37,'Alecrim','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (38,'Alface','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (39,'Alface de iceberg','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (40,'Alface romaina','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (41,'Alfafa','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (42,'Alfarroba','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (43,'Algas','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (44,'Algas vermelhas','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (45,'Algodão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (46,'Alho','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (47,'Alho de pescoço mole','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (48,'Alho-poró','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (49,'Alho-poró selvagem','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (50,'Alimentos ou bebidas não classificados','Indefinido');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (51,'Allium','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (52,'Almôndega','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (53,'Amaranto','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (54,'Âmbar de cauda amarela','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (55,'Amêijoa','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (56,'Ameixa europeia','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (57,'Ameixa java','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (58,'Ameixa malabar','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (59,'Ameixa natal','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (60,'Ameixa preta','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (61,'Ameixa verde','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (62,'Amêndoa','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (63,'Amendoim','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (64,'Amora','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (65,'Amora andina','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (66,'Amora ártica','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (67,'Amora branca','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (68,'Amora de Perdizes','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (69,'Amora preta','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (70,'Amora sem espinhos','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (71,'Amora-branca-silvestre','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (72,'Amora-das-terras altas tropicais','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (73,'Amora-de-sempre-verde','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (74,'Amoreira','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (75,'Anatidae','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (76,'Anchova','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (77,'Anchova','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (78,'Anchova europeia','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (79,'Angélica','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (80,'Anguilliformes','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (81,'Anis','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (82,'Anis-estrelado','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (83,'Araruta','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (84,'Arenque atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (85,'Arenque do Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (86,'Arepa','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (87,'Arinca','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (88,'Arroz','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (89,'Arroz selvagem','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (90,'Arroz selvagem anual','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (91,'Arroz vermelho','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (92,'Artemísia','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (93,'Árvore de rabanete','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (94,'Ascidianos','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (95,'Aspargo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (96,'Aspargos','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (97,'Aterramento','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (98,'Atum albacore','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (99,'Atum azul-do-norte','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (100,'Atum Skipjack','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (101,'Atum-amarelo','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (102,'Aveia','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (103,'Avelã','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (104,'Avelã comum','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (105,'Avestruz','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (106,'Azeite','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (107,'Azeitona','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (108,'Baá-de-china','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (109,'Bacalhau atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (110,'Bacalhau do Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (111,'Badejo','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (112,'Bagel','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (113,'Bagre do canal','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (114,'Baía doce','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (115,'Baixo listrado','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (116,'Baleia beluga','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (117,'Baleia-da-groenlândia','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (118,'Banana','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (119,'Banana francesa','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (120,'Banha','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (121,'Bardana','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (122,'Batata','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (123,'Batata assada','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (124,'Batata frita','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (125,'Batata-doce','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (126,'Baunilha','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (127,'Bayberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (128,'Bebida energética','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (129,'Bebida nutricional','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (130,'Bebida sabor fruta','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (131,'Bebidas','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (132,'Bebidas alcoólicas','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (133,'Beefalo','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (134,'Beicinho da Noruega','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (135,'Beicinho do oceano','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (136,'Beringela','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (137,'Beterraba comum','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (138,'Beterraba vermelha','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (139,'Biênio','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (140,'Bilberry-do-pântano','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (141,'Bisão','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (142,'Biscoito','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (143,'Bivalvia','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (144,'Bolacha','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (145,'Bolinho','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (146,'Bolo','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (147,'Bolo de arroz','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (148,'Bolota','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (149,'Borage','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (150,'Bouillon de carne','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (151,'Boysenberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (152,'branco','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (153,'Brassicas','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (154,'Brócolis','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (155,'Brócolis chinês','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (156,'Brotos de bambu','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (157,'Búfalo','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (158,'Bulgur','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (159,'Burrito','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (160,'Butternut','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (161,'Búzio','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (162,'Cabaça','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (163,'Cabaça amarga','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (164,'Cabaça de cera','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (165,'Cabaça de toalha','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (166,'Cabeça de ovelha','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (167,'Cabra doméstica','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (168,'Cacau em pó','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (169,'Cachorro-quente','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (170,'Café','Produtos de café e café');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (171,'Café arábica','Produtos de café e café');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (172,'Café robusta','Produtos de café e café');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (173,'Cal persa','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (174,'Camarão','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (175,'Camélia-de-semente de óleo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (176,'Camomila alemã','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (177,'Camomila romana','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (178,'Canela','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (179,'Canela chinesa','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (180,'Canela de ceilão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (181,'Canola','Ervas e especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (182,'Cantarelo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (183,'Capim limão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (184,'Caqui','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (185,'Caqui comum','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (186,'Caqui japonês','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (187,'Caracol','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (188,'Caranguejo','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (189,'Caranguejo azul','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (190,'Caranguejo-de-calabouço','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (191,'Caranguejo-neve','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (192,'Caranguejo-rei-vermelho','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (193,'Cardamomo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (194,'Cardo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (195,'Cardo de coalho','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (196,'Carité','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (197,'Carne de ovelha','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (198,'Carpa bream','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (199,'Carpa comum','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (200,'Cártamo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (201,'Caseína','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (202,'Castanha','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (203,'Castanha chinesa','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (204,'Castanha de caju','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (205,'Castanha europeia','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (206,'Castanha-de-água chinesa','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (207,'Castanha-do-pará','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (208,'Castanha-do-pinheiro','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (209,'Castanha-japonesa','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (210,'Castanospermum australe','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (211,'Catchup','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (212,'Caupi','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (213,'Cavala atlântica','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (214,'Cavala espanhola','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (215,'Cavala-de-cavala-de-do-pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (216,'Cavala-rei','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (217,'Cavalo','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (218,'Cebola branca','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (219,'Cebola de jardim','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (220,'Cebola de jardim (var.)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (221,'Cebola galesa','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (222,'Cebola verde','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (223,'Cebola vermelha','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (224,'Cebolinha','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (225,'Cebolinha chinesa','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (226,'Cenoura','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (227,'Cenoura selvagem','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (228,'Centeio','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (229,'Cereais e produtos cereais','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (230,'Cereal','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (231,'Cerefólio','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (232,'Cereja azeda','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (233,'Cereja doce','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (234,'Cereja nanquim','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (235,'Cerveja','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (236,'Cetácea','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (237,'Cevada','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (238,'Chá','Chás');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (239,'Chá de ervas','Chás');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (240,'Chá de hibisco','Chás');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (241,'Chá greenthread','Chás');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (242,'Chá preto','Chás');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (243,'Chá verde','Chás');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (244,'Chá vermelho','Chás');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (245,'Chalota','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (246,'Champanhe branco','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (247,'Champanhe vermelho','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (248,'Charr','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (249,'Cheddar','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (250,'Cheiro de arco-íris','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (251,'Cherimoya','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (252,'Chia','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (253,'Chiclete','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (254,'Chicória','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (255,'Chicory sai','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (256,'Chili','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (257,'Chimichanga','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (258,'Chip de milho','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (259,'Chip de tortilla','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (260,'Chiton de couro','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (261,'Choco','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (262,'Chocolate','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (263,'Chocolate','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (264,'Chocolate quente','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (265,'Chokeberry preto','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (266,'Chokecherry comum','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (267,'Chuchu','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (268,'Cichlidae (Tilápia)','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (269,'Cisco','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (270,'Citrus','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (271,'Clementina','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (272,'Clupeinae','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (273,'Cobertura','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (274,'Cobertura de chocolate','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (275,'Coco','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (276,'Codorniz','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (277,'Coelho','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (278,'Coelho europeu','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (279,'Coentro','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (280,'Cogumelo comum','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (281,'Cogumelo de ostra','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (282,'Cogumelos','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (283,'Colorado pinyon','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (284,'Columbidae','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (285,'Comber pintado','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (286,'Comida de bebê','Alimentos para bebês');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (287,'Comida vegetariana','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (288,'Cominho','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (289,'Concha comestível','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (290,'Concha de taco','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (291,'Cone de sorvete','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (292,'Conservação de frutas','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (293,'Coquetel','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (294,'Corça','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (295,'Cornbread','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (296,'Cornmint','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (297,'Corte frio','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (298,'Couve','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (299,'Couve-chinesa','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (300,'Couve-de-bruxelas','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (301,'Couve-flor','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (302,'Couve-lombarda','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (303,'Couve-rábano','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (304,'Cranberry americano','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (305,'Cranberry europeu','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (306,'Creme azedo','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (307,'Creme de soja','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (308,'Creme doce','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (309,'Crepe','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (310,'Crisântemo de Guirlanda','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (311,'Croaker atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (312,'Croaker spot','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (313,'Crosta de torta','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (314,'Crowberry preto','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (315,'Crustáceos','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (316,'Cucurbita','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (317,'Cupuaã§u','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (318,'Cúrcuma','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (319,'Curry','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (320,'Cuscuz','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (321,'Cusk','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (322,'Dab comum','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (323,'Damasco','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (324,'Data','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (325,'Deerberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (326,'Dendê','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (327,'Dente-de-leão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (328,'Dentes','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (329,'Devilfish','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (330,'Doca','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (331,'Doce alpino','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (332,'Doce marjoram','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (333,'Doce rowanberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (334,'Dulce de leche','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (335,'Durião','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (336,'Eddoe','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (337,'Elderberry preto','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (338,'Empadão','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (339,'Empanada','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (340,'Emu','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (341,'Enchilada','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (342,'Encurtamento','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (343,'Endívia','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (344,'Endro','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (345,'Enguia','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (346,'Enokitake','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (347,'Epazote','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (348,'Erva-cidreira','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (349,'Erva-de-fogo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (350,'Ervas e Especiarias','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (351,'Ervilha catjang','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (352,'Ervilha comum','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (353,'Ervilha de grama','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (354,'Ervilha de olhos negros','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (355,'Ervilha-de-pombo','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (356,'Espadarte','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (357,'Espalhar','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (358,'Espelta','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (359,'Espinafre','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (360,'Espinafre da Nova Zelândia','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (361,'Espinafre de água','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (362,'Espinafre de mostarda','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (363,'Espinafre malabar','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (364,'Espírito','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (365,'Espiulina','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (366,'Estragão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (367,'Estupro','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (368,'Esturjão','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (369,'Faisão','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (370,'Falafel','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (371,'Falsificar','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (372,'Farinha','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (373,'Feijão','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (374,'Feijão','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (375,'Feijão Adzuki','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (376,'Feijão alado','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (377,'Feijão cannellini','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (378,'Feijão comum','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (379,'Feijão de cera amarela','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (380,'Feijão de escalada','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (381,'Feijão de soja','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (382,'Feijão escarlate','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (383,'Feijão-cacau','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (384,'Feijão-de-jarda','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (385,'Feijão-de-lima','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (386,'Feijão-jacinto','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (387,'Feijão-mariposa','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (388,'Feijão-mung','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (389,'Feijoa','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (390,'Feijões cozidos','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (391,'Feno-grego','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (392,'Figo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (393,'Figueira-da-Índia','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (394,'Flor de Sesbania','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (395,'Foca barbuda','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (396,'Focaccia','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (397,'Folhas de aipo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (398,'Framboesa preta','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (399,'Framboesa vermelha','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (400,'Frango','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (401,'Fruta estelar','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (402,'Fruta-do-conde','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (403,'Frutas','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (404,'Frutas lanternas','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (405,'Frutas-monge','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (406,'Frutos do pão','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (407,'Funcho','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (408,'Fundir','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (409,'Fungo de ouvido na nuvem','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (410,'Gadiformes','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (411,'Gado (Carne bovina )','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (412,'Gadus (Bacalhau Comum)','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (413,'Galinha da Guiné','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (414,'Ganso-bravo','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (415,'Garoupa','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (416,'Gelado','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (417,'Gelatina','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (418,'Gema','Ovo');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (419,'Gengibre','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (420,'Gergelim','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (421,'Gim','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (422,'Ginseng','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (423,'Girassol','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (424,'Glacê','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (425,'Goiaba','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (426,'Goiaba de morango','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (427,'Goji','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (428,'Goma de frutas','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (429,'Gordura de manteiga','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (430,'Gorduras e óleos','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (431,'Grão-de-bico','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (432,'Grão-de-grama','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (433,'Grãos de milho','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (434,'Gratinado de batata','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (435,'Graviola','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (436,'Groselha','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (437,'Groselha de búfalo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (438,'Groselha de cabo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (439,'Groselha de gambá','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (440,'Groselha preta','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (441,'Groundcherry mexicana','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (442,'Guaraná','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (443,'Guisado','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (444,'Halibut atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (445,'Halibut do Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (446,'Halibut/turbot da Groenlândia','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (447,'Hambúrguer','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (448,'Hambúrguer de peixe','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (449,'Hambúrguer vegetariano','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (450,'Híbrido grapefruit/Pummelo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (451,'Hipoglosso (halibut comum)','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (452,'Hissopo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (453,'Homus','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (454,'Horchata','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (455,'Hortelã','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (456,'Hortelã-laranja','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (457,'Hortelã-pimenta','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (458,'Huckleberry cascata','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (459,'Huckleberry de folha oval','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (460,'Huckleberry evergreen','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (461,'Huckleberry preto','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (462,'Huckleberry vermelho','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (463,'Hushpuppy','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (464,'Inhame','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (465,'Inhame da montanha','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (466,'Invólucro wonton','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (467,'Iogurte','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (468,'Iogurte congelado','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (469,'Iogurte de soja','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (470,'Jaca','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (471,'Javali','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (472,'Jicama','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (473,'Jostaberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (474,'Jujuba','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (475,'Juniperus communis','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (476,'Juta','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (477,'Kai-lan','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (478,'Komatsuna','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (479,'Kombu','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (480,'Kumquat','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (481,'Lago-lírio amarelo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (482,'Lagosta','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (483,'Lagosta americana','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (484,'Lagosta com garras','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (485,'Lagosta da Noruega','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (486,'Lagostim','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (487,'Lambsquarters','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (488,'Lançamento','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (489,'Lanchonete','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (490,'Laranja áspera','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (491,'Laranja azeda','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (492,'Laranja doce','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (493,'Laranja mandarim','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (494,'Lasanha','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (495,'Laver roxo','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (496,'Leão-marinho steller','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (497,'Lebre da montanha','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (498,'Legumes da família cebola','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (499,'Leite (Humano)','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (500,'Leite (Outros mamíferos)','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (501,'Leite (Vaca)','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (502,'Leite condensado','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (503,'Leite de amêndoa','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (504,'Leite de coco','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (505,'Leite de soja','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (506,'Leite de vaca pausterizado','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (507,'Leite e produtos lácteos','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (508,'Leite em pó','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (509,'Leite evaporado','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (510,'Leitelho','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (511,'Lentilha verde','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (512,'Lentilhas','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (513,'Lichee','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (514,'Licor','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (515,'Licor de cacau','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (516,'Lima','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (517,'Limão','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (518,'Linden de folhas pequenas','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (519,'Linden de prata','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (520,'Ling comum','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (521,'Lingcod','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (522,'Lingonberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (523,'Linhaça','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (524,'Loganberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (525,'Longan','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (526,'Lotus','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (527,'Lótus sagrado','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (528,'Lovage','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (529,'Lua-de-gentiana','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (530,'Lula','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (531,'Lumpsucker','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (532,'Lupine branca','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (533,'Maçã','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (534,'Maçã de açúcar','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (535,'Maçã de cera','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (536,'Maçã mammee','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (537,'Maçã verde','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (538,'Macadâmia','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (539,'Macarrão com queijo','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (540,'Macroalgae','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (541,'Maior esturjão','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (542,'Maitake','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (543,'Malus (maçã caranguejo)','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (544,'Mamão','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (545,'Mandioca','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (546,'Manga','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (547,'Mangosteen roxo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (548,'Manjericão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (549,'Manteiga','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (550,'Manteiga de cacau','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (551,'Manteiga gigante','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (552,'Manteiga salgada','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (553,'Maracujá','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (554,'Margarina','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (555,'Marjoram de maconha','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (556,'Marmelo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (557,'Marshmallow','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (558,'Marzipã','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (559,'Massa','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (560,'Massa','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (561,'Massa azeda','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (562,'Massa Phyllo','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (563,'Meatloaf','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (564,'Medusa','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (565,'Mel','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (566,'Melaço','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (567,'Melancia','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (568,'Melão de cantaloupe','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (569,'Melão-de-chifre','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (570,'Menhaden Atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (571,'Mentha','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (572,'Merengue','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (573,'Mexilhão','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (574,'Mexilhões marinhos','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (575,'Mikan','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (576,'Milhete','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (577,'Milho','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (578,'Milkfish','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (579,'Milkshake','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (580,'Mirtilo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (581,'Mirtilo de Elliott','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (582,'Mirtilo de meia-alta','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (583,'Mirtilo do Alasca','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (584,'Mirtilo do Canadá','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (585,'Mirtilo highbush','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (586,'Mirtilo lowbush','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (587,'Mirtilo-de-coelho','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (588,'Missô','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (589,'Mistura de trilha','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (590,'Mocha de café','Produtos de café e café');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (591,'Molho','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (592,'Molho de soja','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (593,'Moluscos','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (594,'Morango','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (595,'Morchella (Morel)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (596,'Morsa','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (597,'Mostarda','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (598,'Mostarda branca','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (599,'Mostarda chinesa','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (600,'Mostarda de hedge','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (601,'Mousse de chocolate','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (602,'Mundu','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (603,'Musgo irlandês','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (604,'Muskmelon','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (605,'Nabo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (606,'Nabo de pradaria','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (607,'Nachos','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (608,'Nance','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (609,'Naranjilla','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (610,'Nata','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (611,'Natto','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (612,'Nectarina','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (613,'Nêspera','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (614,'Nêspera','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (615,'Nogado','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (616,'Nopal','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (617,'Noruega haddock','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (618,'Noz','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (619,'Nozes','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (620,'Nozes comuns','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (621,'Nozes de ginkgo','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (622,'Nozes japonesa','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (623,'Nozes mistas','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (624,'Nozes preta','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (625,'Noz-moscada','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (626,'Nuttall cockle','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (627,'Ohelo berry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (628,'Óleo de abacate','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (629,'Óleo de algodão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (630,'Óleo de amendoim','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (631,'Óleo de canola','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (632,'Óleo de coco','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (633,'Óleo de colza','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (634,'Óleo de cozinha','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (635,'Óleo de gergelim','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (636,'Óleo de girassol','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (637,'óleo de linhaça','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (638,'Óleo de milho','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (639,'Óleo de soja','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (640,'Óleo de uva','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (641,'Orégano comum','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (642,'Orégano italiano','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (643,'Orégano mexicano','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (644,'Orelha de judeu','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (645,'Ostra do Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (646,'Ostra oriental','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (647,'Ostra verdadeira','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (648,'Outra gordura animal','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (649,'Outra sobremesa congelada','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (650,'Outras bebidas','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (651,'Outras bebidas alcoólicas','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (652,'Outro leite fermentado','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (653,'Outro pão','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (654,'Outro prato','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (655,'Outro prato de massa','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (656,'Outro produto de cacau','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (657,'Outro produto de cereal','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (658,'Outro produto de frutas','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (659,'Outro produto de pão','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (660,'Outro produto de peixe','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (661,'Outro produto de soja','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (662,'Outro sanduíche','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (663,'Outro vinho','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (664,'Outros doces','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (665,'Outros lanches','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (666,'Outros produtos vegetais','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (667,'Ovo','Ovo');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (668,'Pak Choy','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (669,'Palma de Sago','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (670,'Palmeira babaçu','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (671,'Palmito','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (672,'Pan dulce','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (673,'Panqueca','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (674,'Pão árabe','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (675,'Pão branco','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (676,'Pão crocante','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (677,'Pão de arroz','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (678,'Pão de aveia','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (679,'Pão de batata','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (680,'Pão de centeio','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (681,'Pão de fritar','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (682,'Pão de passa','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (683,'Pão de trigo','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (684,'Pão de trigo integral','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (685,'Pão multigrãos','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (686,'Pão piki','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (687,'Papoula','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (688,'Papoula de ópio','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (689,'Passa preta','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (690,'Pastelaria','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (691,'Pastinaca','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (692,'Patê','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (693,'Pato de veludo','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (694,'Pato mallard','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (695,'Pea dispara','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (696,'Pectina','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (697,'Peixe branco largo','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (698,'Peixe gefilte','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (699,'Peixe-achatado','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (700,'Peixe-agulha','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (701,'Peixe-azulejo','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (702,'Peixe-cachorro espinhoso','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (703,'Peixe-carvão-do-pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (704,'Peixe-gato','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (705,'Peixe-golfinho','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (706,'Peixe-lobo-atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (707,'Peixe-manteiga americano','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (708,'Peixe-negro do Alasca','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (709,'Peixe-rocha do Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (710,'Peixes','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (711,'Peixe-sol com sementes de abóbora','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (712,'Pepino','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (713,'Pepino-do-mar','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (714,'Pêra','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (715,'Pera asiática','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (716,'Pera yali','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (717,'Perciformes','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (718,'Percoidei (Baixo e outros)','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (719,'Pérola de tapioca','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (720,'Pêssego','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (721,'Pêssego (var.)','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (722,'Pikeperch','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (723,'Pilriteiro','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (724,'Pimenta','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (725,'Pimenta (C. baccatum)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (726,'Pimenta (C. chinense)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (727,'Pimenta (C. frutescens)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (728,'Pimenta (C. pubescens)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (729,'Pimenta (Capsicum)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (730,'Pimenta (Tempero)','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (731,'Pimenta cubana','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (732,'Pimenta jalapeno','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (733,'Pimenta vermelha doce italiana','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (734,'Pimenta-da-jamaica','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (735,'Pimenta-do-sino de laranja','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (736,'Pimenta-do-sino verde','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (737,'Pimenta-do-sino vermelho','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (738,'Pimentão amarelo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (739,'Pingando','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (740,'Pipoca','Salgadinhos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (741,'Pique do Norte','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (742,'Pistache','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (743,'Pitaia','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (744,'Pitanga','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (745,'Pizza','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (746,'Planícies pera espinhosa','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (747,'Pleuronectidae','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (748,'Pokeweed americano','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (749,'Poleiro do Oceano Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (750,'Pollock','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (751,'Pollock atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (752,'Pollock de peixe-carvão','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (753,'Pollock do Alasca','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (754,'Polvo comum','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (755,'Polvo gigante do Pacífico Norte','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (756,'Pombo','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (757,'Pomes','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (758,'Pompano da Flórida','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (759,'Ponta de flecha','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (760,'Porca de faia','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (761,'Porca de macadâmia (M. tetraphylla)','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (762,'Porca de nozes','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (763,'Porca hickory','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (764,'Porca pili','Nozes');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (765,'Pregado','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (766,'Prímula da noite','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (767,'Produtos de cacau e cacau','Produtos de cacau e cacau');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (768,'Produtos de café e café','Produtos de café e café');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (769,'Propagação semelhante à margarina','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (770,'Prunus','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (771,'Ptarmigan de rocha','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (772,'Pudim','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (773,'Puffs de batata','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (774,'Pulsos','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (775,'Pummelo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (776,'Pupusa','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (777,'Purslane','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (778,'Quadril rosa','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (779,'Quefir','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (780,'Queijo','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (781,'Queijo azul','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (782,'Queijo creme simples','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (783,'Queijo feta grego','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (784,'Queijo fundido','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (785,'Queijo Monterey Jack','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (786,'Queijo mussarela','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (787,'Queijo parmesão','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (788,'Queijo suíço','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (789,'Quesadilla','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (790,'Quiabo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (791,'Quinoa','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (792,'Quivi','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (793,'Rabanada','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (794,'Rabanete','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (795,'Rabanete (var.)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (796,'Rabanete de Daikon','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (797,'Rabanete preto','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (798,'Rabo-de-gato estreito','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (799,'Raízes chicórias','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (800,'Raiz-forte','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (801,'Rambutan','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (802,'Rapini','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (803,'Ravioli','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (804,'Recheio','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (805,'Recheio de torta','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (806,'Redcurrant','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (807,'Refrigerante','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (808,'Remoulade','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (809,'Repolho','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (810,'Repolho branco','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (811,'Repolho comum','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (812,'Repolho de napa','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (813,'Repolho de oxheart','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (814,'Repolho do pântano','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (815,'Repolho preto','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (816,'Repolho tronchuda','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (817,'Repolho verde','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (818,'Requeijão','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (819,'Rio Crosne','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (820,'Robalo japonês','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (821,'Romã','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (822,'Rosela','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (823,'Rowal','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (824,'Rowanberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (825,'Rubus','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (826,'Ruibarbo de jardim','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (827,'Ruibarbo selvagem do Alasca','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (828,'Rum','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (829,'Sábio comum','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (830,'Saborear','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (831,'Sabugueiro','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (832,'Sal','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (833,'Salada','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (834,'Salada','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (835,'Salada de foguete','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (836,'Salada de foguete (ssp.)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (837,'Salada de frutas','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (838,'Salada de milho','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (839,'Salgado de inverno','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (840,'Salgado de verão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (841,'Salgueiro de folha de chá','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (842,'Salmão atlântico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (843,'Salmão chinook','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (844,'Salmão coho','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (845,'Salmão de chum','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (846,'Salmão do Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (847,'Salmão rosa','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (848,'Salmão sockeye','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (849,'Salmonberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (850,'Salmonidae','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (851,'Salsa','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (852,'Salsicha','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (853,'Salsificar comum','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (854,'Salsificar preto','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (855,'Sálvia pineappple','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (856,'Samambaia de árvore','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (857,'Samambaia de aspargos','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (858,'Samambaia de avestruz','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (859,'Sanduíche de café da manhã','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (860,'Sapo verdadeiro','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (861,'Sapodilla','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (862,'Sapote-de-mamey','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (863,'Saquê','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (864,'Sardinha do Pacífico','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (865,'Saskatoon','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (866,'Scombridae','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (867,'Scrapple','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (868,'Scup','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (869,'Sea-buckthornberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (870,'Sebo','Gorduras e óleos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (871,'Selo anelado','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (872,'Selo manchado','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (873,'Semente de árvore de pão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (874,'Sêmola','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (875,'Sheefish','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (876,'Shiitake','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (877,'Sidra','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (878,'Snapper','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (879,'Sobremesa de gelatina','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (880,'Sola de limão','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (881,'Sola verdadeira','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (882,'Sombra americana','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (883,'Sopa','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (884,'Sorgo','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (885,'Soro','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (886,'Sourdock','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (887,'Sparkleberry','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (888,'Substituto de café','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (889,'Substituto de creme','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (890,'Substituto de manteiga','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (891,'Substituto de ovo','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (892,'Substituto do leite','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (893,'Succotash','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (894,'Suco de uva branca','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (895,'Suco de uva vermelha','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (896,'Suco vegetal','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (897,'Sueco','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (898,'Suíno doméstico','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (899,'Sumo de fruta','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (900,'Taco','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (901,'Tainha listrada','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (902,'Talos de aipo','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (903,'Tamale','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (904,'Tamarindo','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (905,'Tambor de água doce','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (906,'Tamboril','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (907,'Tanchagem','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (908,'Taro','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (909,'Tartaruga verde','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (910,'Teff','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (911,'Thunnus','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (912,'Tília','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (913,'Tinda','Cabaças');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (914,'Toffee','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (915,'Tofu','Soja');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (916,'Tomate cereja','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (917,'Tomate de jardim','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (918,'Tomate de jardim (var.)','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (919,'Tomilho comum','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (920,'Tomilho de limão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (921,'Toronja','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (922,'Torta','Confeitaria');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (923,'Tortilha','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (924,'Tostada','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (925,'Tremoço','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (926,'Trevo vermelho','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (927,'Trigo','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (928,'Trigo comum','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (929,'Trigo duro','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (930,'Trigo oriental','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (931,'Trigo-sarraceno comum','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (932,'Trigo-sarraceno tartário','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (933,'Triticale','Cereais e produtos cereais');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (934,'Truta arco-íris','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (935,'Truta do lago','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (936,'Truta marinha','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (937,'Tubarão','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (938,'Tunicado','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (939,'Turquia','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (940,'Ucuhuba','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (941,'Uísque','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (942,'Uva','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (943,'Uva comum','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (944,'Uva de verão','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (945,'Uva muscadina','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (946,'Uva raposa','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (947,'Uva verde','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (948,'Uva vermelha','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (949,'Vaccinium','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (950,'Vagem','Pulsos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (951,'Veado','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (952,'Veado-de-mula','Alimentos de origem animal');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (953,'Vegetais radiculares','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (954,'Vegetais verdes','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (955,'Verbena comum','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (956,'Verbena de limão','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (957,'Verdadeiro selo','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (958,'Verdinho','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (959,'Vermute','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (960,'Vieira','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (961,'Vinagre','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (962,'Vinho branco','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (963,'Vinho de frutas','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (964,'Vinho de sobremesa','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (965,'Vinho de uva','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (966,'Vinho do porto','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (967,'Vinho fortificado','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (968,'Vinho madeira','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (969,'Vinho Rosã©','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (970,'Vinho tinto','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (971,'Vodka','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (972,'Waffle','Louça');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (973,'Wakame','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (974,'Walleye','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (975,'Wampee','Frutas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (976,'Wasabi','Ervas e Especiarias');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (977,'Whelk','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (978,'Whitefish','Alimentos aquáticos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (979,'Xarope','Panificação de produtos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (980,'Xerez','Bebidas');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (981,'Yampah oregon','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (982,'Yau choy','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (983,'Yautia','Verduras');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (984,'Ymer','Leite e produtos lácteos');
INSERT INTO ingrediente(idingrediente,nome,tipo) VALUES (985,'Zwieback','Cereais e produtos cereais');

